from django.urls import path
from . import views
from . import api_views

app_name = 'gestionVentas'
urlpatterns = [
    path(
        '',
        views.HomeView.as_view(),
        name='home'),
    path(
        'sales_list',
        views.listarVentasView.as_view(),
        name='sales_list'),
    path(
        'product_list',
        views.listarProductosView.as_view(),
        name='product_list'),
    path(
        'api/sales/',
        api_views.ListarVentasView.as_view(),
        name='sales_list_api'),
    path(
        'api/products/',
        api_views.ListarProductosView.as_view(),
        name='products_list_api'),
    path(
        'api/info_products/',
        api_views.InfoProductosAPIView.as_view(),
        name='info_products_list_api'),
    path(
        'api/sales_list/',
        api_views.ListarVentasView.as_view(),
        name='sales_list_api'),
    path(
        'add_product',
        views.RegistrarProductoView.as_view(),
        name='add_product'),
    path(
        'update_product/<pk>/',
        views.ActualizarProducto.as_view(),
        name='update_product'),
    path(
        'update_head_sale/<pk>/',
        views.ActualizarDatosVenta.as_view(),
        name='update_head_sale'),
    path(
        'delete_product/<pk>/',
        views.EliminarProductoView.as_view(),
        name='delete_product_view'),
    path(
        'registrar_venta',
        views.RegistrarVentaView.as_view(),
        name='registrar_venta'),
    path(
        'sale_detail/<pk>/',
        views.DetalleVentaView.as_view(),
        name='sale_detail'),
    path(
        'delete_sale/<pk>/',
        views.EliminarVentaView.as_view(),
        name='delete_sale_view'),
    path(
        'delete_item_sale/<pk>/',
        views.EliminarItemVentaView.as_view(),
        name='delete_item_sale_view'),
    path(
        'new_item_sale/<pk>/',
        views.CrearItemVenta.as_view(),
        name='new_item_sale'),
    path(
        'sales_report_excel/',
        views.ReporteVentasView.as_view(),
        name='sales_report_excel'),
    path(
        'product_report_excel/',
        views.ReporteProductosView.as_view(),
        name='product_report_excel'),
    path(
        'update_item_vent/<pk>/',
        views.ActualizarItemVenta.as_view(),
        name='update_item_venta'),
    path(
        'confirm_sale/<pk>/',
        views.ConfirmarVentaView.as_view(),
        name='confirm_sale'),
        ]

