# Generated by Django 5.1.3 on 2024-12-04 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0002_alter_clientes_options'),
        ('gestionVentas', '0003_alter_itemventa_options_alter_venta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventa',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta_items', to='gestionVentas.venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta_cliente', to='abm.clientes'),
        ),
    ]
