# Generated by Django 5.1.3 on 2024-12-06 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0007_venta_fecha_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventa',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_items', to='gestionVentas.producto'),
        ),
    ]
