# Generated by Django 5.1.3 on 2024-12-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0008_itemventa_cantidad_alter_itemventa_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='valor_venta',
            field=models.CharField(max_length=50, verbose_name='Valor ventas'),
        ),
    ]
