# Generated by Django 5.1.3 on 2024-12-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'permissions': [('can_crear_cliente', 'Puede crear Cliente')], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
